name: Build Win7 32 Executable

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Python 3.7.9 (x86)
      uses: actions/setup-python@v4
      with:
        python-version: '3.7.9'
        architecture: 'x86'

    - name: Configure Environment
      shell: powershell
      run: |
        # 获取Python路径（强制ASCII编码）
        $pythonPath = (Get-Command python).Path
        Write-Host "Python Path: $pythonPath"

        # 计算Scripts目录（禁用特殊字符）
        $scriptsDir = Join-Path (Split-Path $pythonPath -Parent) "Scripts"
        Write-Host "Scripts Dir: $scriptsDir"

        # 设置环境变量（仅英文符号）
        $env:PATH = "$scriptsDir;$env:PATH"
        Write-Host "Updated PATH: $env:PATH"

        # 调试：验证路径存在
        Test-Path "$scriptsDir\pyinstaller.exe"

    - name: Install Dependencies
      shell: powershell
      run: |
        # 降级pip（无特殊字符命令）
        python -m pip install --upgrade "pip<21.0"

        # 安装依赖（版本严格匹配）
        pip install pyinstaller==4.10 pywin32==227 pandas==1.1.5 pygame==2.0.3 importlib-metadata==4.8.1

    - name: Build Executable
      shell: powershell
      run: |
        $pythonPath = (Get-Command python).Path
        $scriptsDir = Join-Path (Split-Path $pythonPath -Parent) "Scripts"

        & "$scriptsDir\pyinstaller.exe" --onefile --noconsole `
          --add-data "resources/pop.wav;resources" `
          --hidden-import pandas._libs.tslibs.np_datetime `
          --hidden-import pandas._libs.tslibs.nattype `
          --hidden-import pygame._sdl2 `
          --hidden-import importlib_metadata `
          --target-arch 32bit `
          bubble_app.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: win7-32-exe
        path: dist/bubble_app.exe
