name: Build Windows Executable

on: [push]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 确保检出所有文件
        
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        architecture: "x86"  # 强制32位
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Verify resources
      run: |
        if not test -f pop.wav; then
          echo "错误：缺少pop.wav文件"
          exit 1
        fi
        
    - name: Build exe
      run: |
        mkdir resources
        copy pop.wav resources
        pyinstaller --onefile --noconsole --add-data "resources/pop.wav;resources/" bubble_app.py
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: BubbleApp
        path: dist/bubble_app.exe
