name: Build and Package Python App for Win32

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and run the container
      run: |
        docker run --rm \
          -v $(pwd):/workdir \
          -w /workdir \
          python:3.9-slim-i386 \
          bash -c "pip install pyinstaller pygame pandas numpy && pyinstaller --onefile bubble_app.py"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: win32-app
        path: dist/bubble_app.exe
