name: Build Windows Executable

on: [push]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      shell: powershell
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Verify resources
      shell: powershell
      run: |
        if (-not (Test-Path "resources/pop.wav")) {
          Write-Error "Missing pop.wav in resources/"
          Exit 1
        }
        
    - name: Build executable
      shell: powershell
      run: |
        pyinstaller --onefile --noconsole `
          --add-data "resources/pop.wav;resources" `
          --workpath build `
          --distpath dist `
          bubble_app.py
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: BubbleApp
        path: dist/bubble_app.exe
