name: Build Windows 32bit Executable

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    runs-on: windows-2019  # 使用Windows Server 2019环境
    strategy:
      matrix:
        python-version: ["3.8.10"]  # 使用Python 3.8的32位版本

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python 32bit
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x86'  # 关键：强制使用32位Python

    - name: Install system dependencies
      run: |
        # 安装VC++运行库（可能需要）
        choco install vcredist2010 -y

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller==5.13.2

    - name: Build with PyInstaller
      run: |
        pyinstaller build.spec --onefile --noconsole --runtime-tmpdir . --workpath build --distpath dist

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: BubbleApp-Win32
        path: dist/
