name: Build Windows 7 32-bit Executable

on: [push]

jobs:
  build:
    runs-on: windows-2019  # 兼容性更好的旧版环境
    env:
      PYTHON_ARCH: "x86"   # 强制32位架构

    steps:
    - uses: actions/checkout@v4

    - name: 安装VC++ 2015运行库
      shell: powershell
      run: |
        Invoke-WebRequest -Uri "https://aka.ms/vs/16/release/vc_redist.x86.exe" -OutFile vc_redist.x86.exe
        Start-Process vc_redist.x86.exe -ArgumentList '/install', '/quiet', '/norestart' -Wait

    - name: 配置Python 3.8 32位
      uses: actions/setup-python@v4
      with:
        python-version: "3.8.10"
        architecture: x86  # 关键：必须指定32位

    - name: 安装依赖
      shell: powershell
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip -m install pyinstaller==5.13.2  # 显式安装指定版本
        # 验证安装路径
        Get-ChildItem "$env:USERPROFILE\AppData\Local\Programs\Python\Python38-32\Scripts\pyinstaller.exe"
        pip install -r requirements.txt
        pip list | findstr pyinstaller  # 确认安装成功


    - name: 构建可执行文件
      shell: powershell
      run: |
            # 获取Python安装路径
            $pythonPath = (Get-Command python).Path
            $scriptsDir = Join-Path (Split-Path $pythonPath -Parent) "Scripts"
            
            # 添加路径到环境变量
            $env:PATH = "$scriptsDir;$env:PATH"
            
            # 验证PyInstaller可执行性
            if (-not (Test-Path "$scriptsDir\pyinstaller.exe")) {
                Write-Error "PyInstaller未正确安装!"
                Exit 1
            }
        
            # 执行构建（检查所有符号为英文）
            pyinstaller --onefile --noconsole `
              --add-data "resources/pop.wav;resources" `
              --hidden-import pandas._libs.tslibs.np_datetime `
              --hidden-import pandas._libs.tslibs.nattype `
              --hidden-import pygame._sdl2 `
              --workpath build `
              --distpath dist `
              bubble_app.py
      
    - name: 验证构建结果
      shell: powershell
      run: |
        Get-ChildItem -Path dist -Recurse
        Test-Path "dist/bubble_app.exe"

    - name: 上传制品
      uses: actions/upload-artifact@v4
      with:
        name: BubbleApp-Win7-32bit
        path: dist/bubble_app.exe
