name: Build and Package Python App for Win32

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Upgrade Chocolatey
      run: |
        choco upgrade chocolatey -y

    - name: Uninstall any existing Python installations
      run: |
        choco uninstall python --all-versions -y || true
        choco uninstall python3 --all-versions -y || true

    - name: Clean up residual Python directories
      run: |
        Remove-Item -Recurse -Force "C:\Python39" || true
        Remove-Item -Recurse -Force "C:\ProgramData\chocolatey\lib\python3" || true
        Remove-Item -Recurse -Force "C:\ProgramData\chocolatey\lib-bkp\python3" || true

    - name: Install Python 3.9 (32-bit) with logging
      run: |
        choco install python --version=3.9.0 --x86 -y --install-arguments="'/l*v c:\python3_msi_install.log'"
        # Manually add Python to PATH
        $pythonPath = "$env:SystemDrive\Python39"
        $env:PATH = "$pythonPath;$pythonPath\Scripts;$env:PATH"

    - name: Verify Python Installation
      run: |
        python --version
        pip --version

    - name: Install dependencies
      run: |
        pip install pyinstaller pygame pandas numpy

    - name: Build the application
      run: |
        pyinstaller --onefile bubble_app.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: win32-app
        path: dist/bubble_app.exe

    - name: Upload MSI log
      uses: actions/upload-artifact@v4
      with:
        name: msi-install-log
        path: c:\python3_msi_install.log
