name: Build Win7 32 Executable

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 安装 Python 3.7.9 (32位)
      uses: actions/setup-python@v4
      with:
        python-version: '3.7.9'
        architecture: 'x86'  # 强制32位

    - name: 配置环境变量
      shell: powershell
      run: |
        # 获取Python路径（严格英文符号）
        $pythonPath = (Get-Command python).Path
        Write-Host "Python路径: $pythonPath"

        # 计算Scripts目录
        $scriptsDir = Join-Path (Split-Path $pythonPath -Parent) "Scripts"
        Write-Host "Scripts目录: $scriptsDir"

        # 设置环境变量（英文符号）
        $env:PATH = "$scriptsDir;$env:PATH"
        Write-Host "更新后的PATH: $env:PATH"

    - name: 安装依赖
      shell: powershell
      run: |
        # 降级pip（适配Python 3.7）
        python -m pip install --upgrade "pip<21.0"

        # 安装兼容库
        pip install pyinstaller==4.10 pywin32==227 pandas==1.1.5 pygame==2.0.3

    - name: 构建可执行文件
      shell: powershell
      run: |
        # 使用绝对路径调用PyInstaller
        $pythonPath = (Get-Command python).Path
        $scriptsDir = Join-Path (Split-Path $pythonPath -Parent) "Scripts"
        
        & "$scriptsDir\pyinstaller.exe" --onefile --noconsole `
          --add-data "resources/pop.wav;resources" `
          --hidden-import pandas._libs.tslibs.np_datetime `
          --hidden-import pandas._libs.tslibs.nattype `
          --hidden-import pygame._sdl2 `
          --target-arch 32bit `  # 强制32位
          bubble_app.py

    - name: 上传产物
      uses: actions/upload-artifact@v4
      with:
        name: win7-32-executable
        path: dist/bubble_app.exe
