name: Build Windows Executable

on: [push]

jobs:
  build:
    runs-on: windows-latest  # 使用微软提供的Windows虚拟机
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"  # 兼容Win7的Python版本
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Build exe
      run: |
        pyinstaller --onefile --noconsole --add-data "pop.wav;." bubble_app.py
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: BubbleApp
        path: dist/
