name: Build and Package Python App for Win32

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Chocolatey
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

    - name: Install Python 3.9 (32-bit)
      run: |
        choco install python --version=3.9.0 --x86 -y
        # Manually add Python to PATH
        $pythonPath = "$env:SystemDrive\Python39"
        $env:PATH = "$pythonPath;$pythonPath\Scripts;$env:PATH"

    - name: Verify Python Installation
      run: |
        python --version
        pip --version

    - name: Install dependencies
      run: |
        pip install pyinstaller pygame pandas numpy

    - name: Build the application
      run: |
        pyinstaller --onefile bubble_app.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: win32-app
        path: dist/bubble_app.exe
